---
title: "1.4 — Can We Plan an Economy? — Class Content"
draft: false
linktitle: "1.4 — Can We Plan an Economy?"
date: "2020-06-08"
menu:
  content:
    parent: Course content
    weight: 2
type: docs
output:
  blogdown::html_page:
    toc: true
slides: "1.4-slides"
---

{{% alert note %}}
*Thursday, September 2, 2021*
{{% /alert %}}

## <i class="fas fa-info-circle fa-lg"></i> Overview

Today we begin considering how to measure development. 

## <i class="fas fa-book-reader fa-lg"></i> Readings

# Recommended Readings:

- [<i class="fas fa-external-link-square-alt"></i> "The Reductive Seduction of Other People's Problems"](https://brightthemag.com/the-reductive-seduction-of-other-people-s-problems-3c07b307732d)
- [<i class="fas fa-podcast"></i> NPR's *Planet Money*: "The Invention of the Economy"](https://www.npr.org/sections/money/2014/03/05/286366404/episode-521-the-invention-of-the-economy)
- [<i class="fab fa-youtube"></i> "What if There Were No Prices?"](https://www.youtube.com/watch?v=zkPGfTEZ_r4)
- [<i class="fas fa-external-link-square-alt"></i> Marx and Engels, 1848, *Manifesto of the Communist Party*](https://www.marxists.org/archive/marx/works/1848/communist-manifesto/)

See also the next readings for more in anticipation of our discussion next class.

## <i class="fas fa-chalkboard-teacher"></i> Slides

Below, you can find the slides in two formats. Clicking the image will bring you to the html version of the slides in a new tab. Note while in going through the slides, you can type <kbd>h</kbd> to see a special list of viewing options, and type <kbd>o</kbd> for an outline view of all the slides.

The lower button will allow you to download a PDF version of the slides. I suggest printing the slides beforehand and using them to take additional notes in class (*not everything* is in the slides)!

`r blogdown::shortcode("slide-links")`