---
title: "2.3 — The Macroeconomics of Development I: Classical Growth Theory — Class Content"
draft: false
linktitle: "2.3 — Macroeconomics of Development I: Classical Growth Theory"
date: "2020-06-08"
menu:
  content:
    parent: Course content
    weight: 8
type: docs
output:
  blogdown::html_page:
    toc: true
slides: "2.3-slides"
---

{{% alert note %}}
*Thursday, September 16, 2021*
{{% /alert %}}

## <i class="fas fa-info-circle fa-lg"></i> Overview

Here we explore the famous growth models of an economy. This lesson will be the most technical of the semester, but remember there are no homeworks or exams that have you use the models to calculate equilibrium outcomes. It is more important that you understand the basic mechanisms and the major conclusions of the models. Modern economic development, macroeconomics, and public policy literatures and debates rely heavily on these models!

We begin with a short history of economic thought on growth, from the mercantilists and classicals through the famous neoclassical models and their extensions in the 1950s-1980s. Before we reach the major growth models, we mention, among others, David Ricardo for his insistence on diminishing returns and the steady state, the Harrod-Domar model for the first major milestone in growth modeling, and Nicholas Kaldor for his famous "stylized facts" that growth models must explain.

In thinking about how to "model" an economy in a way that policymakers can exploit (e.g. manipulate key choice variables that can be changed) and assess the results, consider again: what exactly are we able to control? What knowledge must policymakers possess? What incentives ensure it gets implemented "the way we want?"

## <i class="fas fa-book-reader fa-lg"></i> Readings

# Optional/Referenced Readings:

- [<i class="fas fa-file-pdf"></i> Nordhaus (2000), "Do Real-Output and Real-Wage Measures Capture Reality?"](https://www.nber.org/chapters/c6064.pdf)
- [<i class="fas fa-podcast"></i> *NPR Planet Money Podcast*: The History of Light, Nobel Edition "](https://www.npr.org/sections/money/2018/10/08/655597272/episode-534-the-history-of-light-nobel-edition)

## <i class="fas fa-chalkboard-teacher"></i> Slides

Below, you can find the slides in two formats. Clicking the image will bring you to the html version of the slides in a new tab. Note while in going through the slides, you can type <kbd>h</kbd> to see a special list of viewing options, and type <kbd>o</kbd> for an outline view of all the slides.

The lower button will allow you to download a PDF version of the slides. I suggest printing the slides beforehand and using them to take additional notes in class (*not everything* is in the slides)!

`r blogdown::shortcode("slide-links")`

## Interactive Solow Model

- [Visualizing the Solow Model](https://ryansafner.shinyapps.io/Solow/)

This is an example that I wrote in R/Shiny in previously, to visualize what it is we are looking at in the Solow Model. As I find more time, I may update this and integrate it into our slides, but until then, I will just post a link. 

You can adjust things about the (Cobb-Douglas) production function, savings rate, depreciation rate, population growth rate, and TFP growth rate, and see how it would affect the graph and the equilibrium. 

Note I have not added calculations or the golden rule yet. Moving $k$ around just shows where $k$ would start, and then it would have to grow/shrink to get to $k^*$. 

## Math Appendix

### Cobb-Douglas Functions

A Cobb-Douglas function takes the form: 

$$y=Ax_1^\alpha x_2 ^\beta$$

It is often used for utility functions $(y$ is utility, $x_1$ and $x_2$ are goods) and production functions $(y$ is output, $x_1$ and $x_2$ are factors of production, such as $L$ and $K).$

It is often converted into logarithmic form by taking the natural logs:

$$ln \, y = ln \, A + \alpha \, ln \, x_1 + \beta \, ln \, x_2$$

This function is (surprisingly) easy to work with for its many useful properties:

1. Returns to scale
    - If $\alpha+\beta > 1$: increasing returns to scale
    - If $\alpha+\beta = 1$: constant returns to scale
    - If $\alpha+\beta < 1$: decreasing returns to scale

2. Elasticities/Shares
    - In the constant returns to scale case (the exponents sum to 1), often rewritten as $y=Ax_1^{\alpha}x_2^{1-\alpha}$:
        - $\alpha$ represents the (fraction of income spent - in utility case; output elasticity - in production case) of each $x_i$
            - e.g. if $u=x^{0.4}y^{0.6}$, consumer spends 40% of income on $x$ and 60% on $y$
            - e.g. if $y=K^{0.4}L^{0.6}$, a 1% increase in $K$ generates a $0.4$% increase in $y$
            - Aggregate Production Function case: $\alpha$ is the "share" of output or income going to each factor

3. Desirable shape of function
    - Convex
    - Positive but diminishing returns to each $x_i$, $\left(\frac{\partial y}{\partial x_i} > 0, \, \frac{\partial^2 y}{\partial x_i^2} < 0 \right)$

See more on Cobb-Douglas functions from my ECON 306 - Microeconomic Analysis course notes:

- [Cobb Douglas Utility Functions](https://microf21.classes.ryansafner.com/content/1.3-content/#cobb-douglas-functions)
- [Constrained Optimization with Cobb-Douglas](https://microf21.classes.ryansafner.com/content/1.4-content/#solving-the-constrained-optimization-problem-with-calculus)
- [Deriving Demand from Cobb-Douglas Utility](https://microf21.classes.ryansafner.com/content/1.4-content/#solving-the-constrained-optimization-problem-with-calculus)

For production, simply replace $u$ with $y$, and $x$ and $y$ with $l$ and $k$.
