---
title: "3.1 — Foreign Aid I: Growth Regressions, Program Evaluation, & Aid Theory — Class Content"
draft: false
linktitle: "3.1 — Foreign Aid I: Growth Regressions, Program Evaluation, & Aid Theory"
date: "2020-06-08"
menu:
  content:
    parent: Course content
    weight: 11
type: docs
output:
  blogdown::html_page:
    toc: true
slides: "3.1-slides"
---

{{% alert note %}}
*Thursday, September 30, 2021*
{{% /alert %}}

{{% alert warning %}}
We will have our next discussion on Tuesday, October 3. Please see the required [readings](/content/3.2-content) for next class.
{{% /alert %}}

## <i class="fas fa-info-circle fa-lg"></i> Overview

This week we consider a controversial topic, the role of foreign aid in promoting economic development (growth) in developing countries. I don't want to lecture too much, as our reading can provide much better insight, as Easterly was a central participant in this debate. 

Today I will start with a technical overview of empirical research in economic development. I will then give you an overview of the history of foreign aid and its major stages/programs (structural adjustment lending, etc.), the theoretical arguments for aid's necessity (Harrod-Domar model, financing gap/poverty trap, etc) and a next class will be an empirical assessment of its effectiveness (and our discussion). 

## <i class="fas fa-book-reader fa-lg"></i> Readings

## Required Reading

- <i class="fas fa-book"></i> Chapters 2,6 in Easterly, 2002, *The Elusive Quest for Growth*

## <i class="fas fa-chalkboard-teacher"></i> Slides

Below, you can find the slides in two formats. Clicking the image will bring you to the html version of the slides in a new tab. Note while in going through the slides, you can type <kbd>h</kbd> to see a special list of viewing options, and type <kbd>o</kbd> for an outline view of all the slides.

The lower button will allow you to download a PDF version of the slides. I suggest printing the slides beforehand and using them to take additional notes in class (*not everything* is in the slides)!

`r blogdown::shortcode("slide-links")`