---
title: "3.3 — Geography: The Diamond Hypothesis — Class Content"
draft: false
linktitle: "3.3 — Geography: The Diamond Hypothesis"
date: "2020-06-08"
menu:
  content:
    parent: Course content
    weight: 12
type: docs
output:
  blogdown::html_page:
    toc: true
slides: "3.3-slides"
---

{{% alert note %}}
*Thursday, October 14, 2021*
{{% /alert %}}

## <i class="fas fa-info-circle fa-lg"></i> Overview

We come to the last key arguments for what causes some nations to become wealthy and others poor. While we cannot cover an exhaustive list of important factors (this class would be several semesters), we can cover the remaining major arguments. I will over-simplify and lump several into what we might call "geographic determinism:" countries are destined to be wealthy or poor based on their geographies.

This comes into play in several ways, first, the famous geographic determinist argument in Jared Diamond's famous *Guns, Germs, and Steel*: regions that span across a single latitude (East-West) were destined to develop before those that span across longitude (North-South) due to climate and geographically-driven variation domesticable plant and animal species.

## <i class="fas fa-book-reader fa-lg"></i> Readings

## Required Reading

- <i class="fas fa-book"></i> Chapter 2 in Acemoglu and Robinson, 2012, *Why Nations Fail*
- [<i class="fas fa-file-pdf"></i> Sachs, Mellinger, and Gallup (2001), "The Geography of Poverty"](/readings/Sachs-Mellinger-Gallup-2001.pdf)

## Primary Sources Mentioned

- [<i class="fas fa-file-pdf"></i> Alsan (2015), "The Effect of the Tse Tse Fly on African Development"](/readings/Alsan-2015.pdf)
- [<i class="fas fa-file-pdf"></i> Baird, Hicks, Kremer, and Miguel (2016), "Worms at Work: Long-Run Impacts of a Child Health Investment"](/readings/Baird-Hicks-Kremer-Miguel-2016.pdf)
- [<i class="fas fa-file-pdf"></i> Comin, Easterly, and Gong (2010), "Was the Wealth of Nations Determined in 1000 BC?"](/readings/Comin-Easterly-Gong-2010.pdf)
- [<i class="fas fa-file-pdf"></i> Gallup, Sachs, and Mellinger (1999), "Geography and Economic Development"](/readings/Gallup-Sachs-Mellinger-1999.pdf)
- [<i class="fas fa-file-pdf"></i> Rodrik, Subramanian, and Trebbi (2002), "Institutions Rule: The Primacy of Institutions Over Geography and Integration in Economic Development"](https://www.nber.org/papers/w9305.pdf) 
- [<i class="fas fa-file-pdf"></i> Sachs, Mellinger, and Gallup (2001), "The Geography of Poverty"](/readings/Sachs-Mellinger-Warner-Gallup.pdf)
- [<i class="fas fa-file-pdf"></i> Spolaore and Wacziarg (2013), "How Deep are the Roots of Economic Development"](/readings/Spolaore-Wacziarg-2013.pdf)

## Questions to Read For

- Advocates for foreign aid, such as Sachs, cite the very real successes in health outcomes in the Developing world (e.g. infant mortality rates, malaria and tuberculosis rates, etc). Is this about *economic growth* or something else?

- Read Easterly (2015)'s short book review in the Wall Street Journal. What does Easterly say aid has been *successful* for?

- Perhaps we just need *better*, more targetted, *smarter* (in whatever metric chosen) foreign aid?

- What can foreign aid do *well*? See Skarbek and Leeson (2009) for more.

- Some papers (e.g. Burnside and Dollar, 2000) find that receiving aid can boost growth under the right conditions (good institutions, good policies, good governance, etc).

- We specifically focused on foreign aid intended to improve economic development (GDP per capita growth) in low-income countries. What do you think about the role of *other* types of foreign aid for other purposes? Does it accomplish *those* purposes? Is this related to *economic* development as well?

- What, specifically, went wrong with structural adjustment lending?

- Look at the list of recommendations that comprise the "Washington Consensus" (slide 9, or see Rodrik 2006). Which of these do you agree or disagree with? If you agree with some or all, what's wrong with these?

- Easterly's common refrain is that these (and other policies) are not compatible with the phrase "people respond to incentives." What does he mean, specifically? Do you agree?

- What are the incentives of the governments of donor countries and their constituents? What are the incentives of the governments of recipient countries'?

- What do you make of Easterly's proposed "Scrooge" development agency?

- Take financing gap/poverty trap argument. Do you agree with its premises (growth requires investment, investment requires savings, low-income people/countries can't save)? If you *do*, doesn't the conclusion seem inevitable?

- If developing countries are supposed to grow with foreign aid, pr are unable to grow without it, how did the countries that are wealthy today get rich? From "foreign aid?" 

- Foreign aid for growth is a transfer between government and government (a wealthy donor country's government gives to a poor country's government). Regardless of how you feel about the arguments for/against foreign aid for growth, what would be different if at least one side (donor/recipient) were *not* a government? Income, investment, and finance coming from other countries can come from sources *other* than governments, and be given *to* recipients other than governments. What about the private sector, civil society, non-profits, family remittances, etc?
## <i class="fas fa-chalkboard-teacher"></i> Slides

Below, you can find the slides in two formats. Clicking the image will bring you to the html version of the slides in a new tab. Note while in going through the slides, you can type <kbd>h</kbd> to see a special list of viewing options, and type <kbd>o</kbd> for an outline view of all the slides.

The lower button will allow you to download a PDF version of the slides. I suggest printing the slides beforehand and using them to take additional notes in class (*not everything* is in the slides)!

`r blogdown::shortcode("slide-links")`