---
title: "4.1 — Introduction to Political Economy"
draft: false
linktitle: "4.1 — Introduction to Political Economy"
date: "2020-06-08"
menu:
  content:
    parent: Course content
    weight: 14
type: docs
output:
  blogdown::html_page:
    toc: true
slides: "4.1-slides"
---

{{% alert note %}}
*Tuesday, October 26* and *Thursday, October 28, 2021*
{{% /alert %}}

{{% alert warning %}}
We will have a discussion **Tuesday, November 2** on the required readings below.
{{% /alert %}}

## <i class="fas fa-info-circle fa-lg"></i> Overview

We finally begin discussing institutions and their role in economic development. First, we discuss some motivating problems of *political economy*, the knowledge problem & incentive problem, that different societies try to solve with various institutions. We discuss some of the more specific political-economic problem that must be addressed: that self-interested people will find ways to benefit themselves, even if it comes at the expense of others. What we would *like* is to create institutions and rules that channel that fundamental motivation into *productive* outcomes that benefit society, rather than outcomes that only benefit the person, and are *unproductive* or *destructive* towards society. In doing so, we contrast profit-seeking with rent-seeking, the latter of which can cause unproductive and destructive outcomes.

## <i class="fas fa-book-reader fa-lg"></i> Readings

## Required Reading

- <i class="fas fa-book"></i> Chapter 3 in Acemoglu and Robinson, 2012, *Why Nations Fail*

Chapter 3 outlines the central thesis of the book: that differences in income per capita around the world today, and the trajectories of economic development are determined by political and economic institutions. AJR^[The common nickname for "Acemoglu, Johnson, and Robinson", who frequently collaborate on these issues (see the primary sources below).] distinguish between "inclusive institutions" and "extractive institutions," and describe how the distribution of political power affects political institutions, which in turn affect economic institutions, which affects a nation's ability to sustain economic growth.  

## Strongly Recommended

- <i class="fas fa-book"></i> Chapter 1 in Acemoglu and Robinson, 2012, *Why Nations Fail*

Chapter 1 sets the stage with a number of stories that emphasize the differences in inclusive vs. extractive institutions, primarily by comparing the colonization experience of the Spanish in South/Central America and the English in North America.

## Primary Sources

- [<i class="fas fa-file-pdf"></i> Stigler (1971), "The Theory of Economic Regulation"](/readings/Stigler-1971.pdf)
- [<i class="fas fa-file-pdf"></i> Kreuger (1974), "The Political Economy of the Rent-Seeking Society"](/readings/Kreuger-1974.pdf)
- [<i class="fas fa-file-pdf"></i> Acemoglu and Robinson (2000), "Political Losers as a Barrier to Economic Development"](/readings/Acemoglu-Robinson-2000.pdf)
- [<i class="fas fa-file-pdf"></i> Acemoglu, Johnson, and Robinson (2001), "The Colonial Origins of Comparative Development: An Empirical Investigation"](/readings/Acemoglu-Johnson-Robinson-2001.pdf)
- [<i class="fas fa-file-pdf"></i> Acemoglu and Johnson (2005), "Unbundling Institutions"](/readings/Acemoglu-Johnson-2005.pdf)
- [<i class="fas fa-file-pdf"></i> Baumol (1990), "Entrepreneurship: Productive, Unproductive, and Destructive"](/readings/Baumol-1990.pdf)
- [<i class="fas fa-file-pdf"></i> Tullock (1967), "The Welfare Cost of Tariffs, Monopolies, and Theft"](/readings/Tullock-1967.pdf)
- [<i class="fas fa-file-pdf"></i> Murphy, Shleifer, Vishny (1991), "The Allocation of Talent: Implications for Growth"](/readings/Murphy-Shleifer-Vishny-1991.pdf)
- [<i class="fas fa-file-pdf"></i> Glaesar et. al (2004), "Do Institutions Cause Growth?"](/readings/Glaesar-et-al-2004.pdf)
- [<i class="fas fa-file-pdf"></i> Mitchell (2012), "The Pathology of Privilege — The Economic Consequences of Government Favoritism"](/readings/Mitchell-2012.pdf)
- [<i class="fas fa-file-pdf"></i> Munger and Villareal-Diaz (2019), "The Road to Crony Capitalism"](/readings/Munger-Villareal-Diaz-2019.pdf)

## Questions to Read For

- What does Baumol mean that entrepreneurship can be "productive," "unproductive," or "destructive," and what role do institutions play?

- What is the problem with "finding the right people" to elect/appoint to govern a society?

- Related to the previous question, how do the knowledge and incentive problems affect how we govern society? What does a society that is *robust* to those problems mean, or look like?

- What is the nirvana fallacy?

- Why do people make different assumptions about how consumers make (selfish/irrational/foolish/etc) choices in a market economy, vs. the how (the same!) people make (wise/public-spirited) choices in politics (as voters, elected officials, dictators, etc)? What are the implications of assuming *the same* people are guided by self-interest in these different arenas?

- What is the different between profit-seeking and rent-seeking? What role do institutions play in creating/changing the difference?

- According to Acemoglu and Robinson, what is the difference between “inclusive” institutions and “extractive” institutions?

- According to Acemoglu and Robinson, why is it *political* losers, rather than *economic* losers, that are more likely to block creative destruction and innovation?

- Acemoglu, Johnson, and Robinson argue that a major cause of differences in GDP per capita today come from historical institutions, especially in former colonies, the type of colony that was set up hundreds of years ago — either inclusive or extractive. One of the primary factors determining *what type* of colony Europeans chose to set up was *disease* — is this geography affecting development (through institutions) all over again?


## <i class="fas fa-chalkboard-teacher"></i> Slides

Below, you can find the slides in two formats. Clicking the image will bring you to the html version of the slides in a new tab. Note while in going through the slides, you can type <kbd>h</kbd> to see a special list of viewing options, and type <kbd>o</kbd> for an outline view of all the slides.

The lower button will allow you to download a PDF version of the slides. I suggest printing the slides beforehand and using them to take additional notes in class (*not everything* is in the slides)!

`r blogdown::shortcode("slide-links")`