---
title: "4.2 — Limited Access Orders & The Natural State"
draft: false
linktitle: "4.2 — Limited Access Orders & The Natural State"
date: "2020-06-08"
menu:
  content:
    parent: Course content
    weight: 15
type: docs
output:
  blogdown::html_page:
    toc: true
slides: "4.3-slides"
---

{{% alert note %}}
*Tuesday, November 9, 2021*
{{% /alert %}}

{{% alert warning %}}
We will have a discussion **Tuesday, November 18** on the required readings for [next class](/content/4.3-content).
{{% /alert %}}

## <i class="fas fa-info-circle fa-lg"></i> Overview

This week we continue our discussion of economic history under low state capacity and discuss two aspects. 

Today we examine what were most "States" like before the modern era. We know they are unable to tax or do very much by modern standards, but it certainly was not pure anarchy. For nearly all of human history since settled agriculture, people have (at least nominally) been the subjects of an autocrat. This is a catch-all term for a non-democratically-elected ruler, such as a king/queen, emperor/empress, dictator, etc. 

Olson provided us with one framework for understanding the incentives of the ruler: a revenue-maximizing stationary bandit, which is preferable to the anarchy of roving bandits. We consider first another model, North Wallis and Weingast (2011)’s “limited access orders” or “the natural state” that describe how these states operate, and why they were a stable equilibrium for thousands of years, and the majority of countries, by the numbers, remain in this equilibrium today.

## <i class="fas fa-book-reader fa-lg"></i> Readings


### Recommended

- [<i class="fas fa-book"></i>Chapter 1 in North, Wallis, Webb, Weingast (2013) *In the Shadow of Violence: Politics, Economics, and the Problems of Development*](/readings/North-Wallis-Webb-Weingast-2013.pdf)

This chapter (from an edited volume of essays) outlines the theory of what North, Wallis, and Weingast call "limited-access orders" (LAOs) in contrast to "open access orders." Their theory is fully spelled out in the excellent book *Violence and Social Orders* (2009), where they alternatively call limited access orders "natural states." This will give you an overview of the difference, and, importantly, how LAOs work, and why all societies either *once* were LAOs (but have since developed into open access orders), or *remain* LAOs.


### Questions to Read For:

- We pretty much know what policies and institutions generate prosperity (property rights, rule of law, etc). Leaders of developing countries probably know this as well (or can quickly find out). Why don't they implement them? Or, more accurately, what would happen if they implement them?
- What is the difference between the State and the Mafia?
- How does a Limited Access Order (LAO, also called "natural state") function?
- What are the differences between a Limited Access Order and an Open Access Order? How does one transition to the other?
- Successful societies "*wage peace.*" Explain how this is an apt summary for the politics of a LAO/natural state.

## <i class="fas fa-chalkboard-teacher"></i> Slides

Below, you can find the slides in two formats. Clicking the image will bring you to the html version of the slides in a new tab. Note while in going through the slides, you can type <kbd>h</kbd> to see a special list of viewing options, and type <kbd>o</kbd> for an outline view of all the slides.

The lower button will allow you to download a PDF version of the slides. I suggest printing the slides beforehand and using them to take additional notes in class (*not everything* is in the slides)!

`r blogdown::shortcode("slide-links")`