---
title: "4.4 — Selectorate Model & The Violence Trap"
draft: false
linktitle: "4.4 — Selectorate Model & The Violence Trap"
date: "2020-06-08"
menu:
  content:
    parent: Course content
    weight: 16
type: docs
output:
  blogdown::html_page:
    toc: true
slides: "4.4-slides"
---

{{% alert note %}}
*Thursday, November 11* and *Tuesday November 16, 2021*
{{% /alert %}}

{{% alert warning %}}
We will have a discussion **Thursday, November 18** on the required readings below.
{{% /alert %}}

## <i class="fas fa-info-circle fa-lg"></i> Overview

Today we look at a second model of how autocrats behave, known as “selectorate theory.”

Second, we consider why countries today do not suddenly switch from autocracy to democracy, or, when they try to, they often revert right back into autocracy (consider the famed Arab Spring and its aftermath). This is the idea of the “violence trap,” that a sub-optimal equilibrium is stable, and even if a more-preferable equilibrium is within sight, the transition to get there is fraught with peril and violence (perhaps a period of roving bandits?), and worse than the sub-optimal equilibrium.


## <i class="fas fa-book-reader fa-lg"></i> Readings

### Required

- [<i class="fas fa-book"></i>Chapter 1 in North, Wallis, Webb, Weingast (2013) *In the Shadow of Violence: Politics, Economics, and the Problems of Development*](/readings/North-Wallis-Webb-Weingast-2013.pdf)
- [<i class="fas fa-podcast"></i> *Econtalk* (2006): "Bruce Bueno de Mesquita on the Political Economy of Power"](http://www.econtalk.org/archives/2006/08/the_political_e.html)

This chapter (from an edited volume of essays) outlines the theory of what North, Wallis, and Weingast call "limited-access orders" (LAOs) in contrast to "open access orders." Their theory is fully spelled out in the excellent book *Violence and Social Orders* (2009), where they alternatively call limited access orders "natural states." This will give you an overview of the difference, and, importantly, how LAOs work, and why all societies either *once* were LAOs (but have since developed into open access orders), or *remain* LAOs.

The podcast is with Bruce Bueno de Mesquita on *Econtalk* (One of the original episodes back in 2006!) talking about his book (with coauthors), *The Logic of Political Survival*. It is a wide-ranging conversation, but centers on his "Selectorate theory," and how this model explains both autocratic and democratic behavior. Some development concepts, including foreign aid, are discussed. Very eye-opening. This is an alternative to assigning more book chapters or papers. See the description of each below.

### Recommended

- [<i class="fas fa-file-pdf"></i> Cox, North, and Weingast (2015), "The Violence Trap"](/readings/Cox-North-Weingast-2015.pdf)
- [<i class="fas fa-podcast"></i> *Econtalk* (2013): "Barry Weingast on the Violence Trap"](http://www.econtalk.org/archives/2013/08/weingast_on_the.html)

The podcast (and the paper it is based off of) is Barry Weingast on *Econtalk* talking about the "violence trap." This idea is strongly connected to North, Wallis, and Weingast's LAOs/Natural State framework. Reforms of the political and economic system that might improve economic development (and GDP/capita) and lead to a more open access order are often prevented by ruling elites. It is neither in their interest to open up, and it might provoke chaos, disorder, and violence in a society (think Olson's roving bandits). Such a tumultous outcome, while it has a chance of leading to democracy and wealth, is a worse outcome than the existing system, as unfair, inefficient, and peverse as it may be. This is the violence trap.

### Primary Sources

- [<i class="fas fa-book"></i> Bueno de Mesquita, Smith, Siverson, and Morrow (2005) *The Logic of Political Survival*](https://www.amazon.com/Logic-Political-Survival-MIT-Press/dp/0262524406)
- [<i class="fas fa-book"></i> North, Wallis, and Weingast (2009) *Violence and Social Orders: A Conceptual Framework for Interpreting Recorded Human History*](https://www.amazon.com/Violence-Social-Orders-Conceptual-Interpreting/dp/1107646995)
- [<i class="fas fa-file-pdf"></i> Tullock (1971), "The Paradox of Revolution"](/readings/Tullock-1971.pdf)
- [<i class="fas fa-file-pdf"></i> Kuran (1989), "Sparks and Prarie Fires: A Theory of Unanticipated Political Revolution"](/readings/Kuran-1989.pdf)


### Questions to Read For:

- What do economists miss when they focus only on "the light side of the force" i.e. voluntary exchange and trade? What can we learn from studying violence and coercion as well?
- We pretty much know what policies and institutions generate prosperity (property rights, rule of law, etc). Leaders of developing countries probably know this as well (or can quickly find out). Why don't they implement them? Or, more accurately, what would happen if they implement them?
- What is the difference between the State and the Mafia?
- Bueno de Mesquita's "selectorate" theory is also famous for a much more complex (yet verifiable!) application of Olson's logic. What is the selectorate? How is the selectorate different for democracies and non-democracies? What is the "winning/dominant coalition"?
- How does the allocation of public goods vs. private goods (i.e. rents for cronies) differ based on the selectorate? 
- Is a dictator all-powerful? Why or why not?
- Why does it commonly appear that support for an oppressive regime is higher than it actual is?
- Why are there few (or no?) success stories of popular revolutions that overthrew an autocratic government and replaced it with a democratic government?

## <i class="fas fa-chalkboard-teacher"></i> Slides

Below, you can find the slides in two formats. Clicking the image will bring you to the html version of the slides in a new tab. Note while in going through the slides, you can type <kbd>h</kbd> to see a special list of viewing options, and type <kbd>o</kbd> for an outline view of all the slides.

The lower button will allow you to download a PDF version of the slides. I suggest printing the slides beforehand and using them to take additional notes in class (*not everything* is in the slides)!

`r blogdown::shortcode("slide-links")`