---
title: "Final Exam"
draft: false
#linktitle: "Instructions"
date: "2020-06-08"
menu:
  assignments:
    parent: Exams
    weight: 1
type: docs
output:
  blogdown::html_page:
    toc: false
---

```{r message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(pander)
```

{{% alert warning %}}
Due by 2:00 PM **Tuesday December 14** by email.
{{% /alert %}}

# Instructions

Choose three (3) questions from Section I and two (2) from Section II (5 questions in total) to answer. **Each question is worth 20 points.**

Questions draw from course lectures, discussions, and readings. Your answers, given the time and resources at your disposal, should be complete yet concise (e.g. 2-3 well-reasoned paragraphs).

**Please do not answer more than the required number of questions.** If you do, I will only grade the first 3 from Section I and 2 from Section II.

You may discuss the questions, but you must write your own responses and turn in your own work. Answers that are substantially similar will be interpreted as cheating and punished accordingly. I will not answer any questions about course content during while the exam is outstanding.

You will be graded both on your use of reasoning and economic analysis, and ability when relevant to accurately describe the arguments in the readings. Where asked for your opinion, you will not be graded on your *conclusion*, only your *reasoning.* You must be able to talk with some familiarity about arguments put forth in our readings, when relevant (informally, as in “According to Easterly...”). You do not need formal citations, but it should be clear when you are referencing the readings vs. your own thinking.

This assignment is due to me by email by 2:00 PM on Tuesday December 14. Starting at 2:01, you will lose 2 points for every hour late.

# Section I (Models & Frameworks) — Choose Three (3)

## Question 1

Critically appraise the role of the Solow (exogenous) growth model in understanding economic growth, and explaining the variation between countries growth rates. What has been its impact on research in economic growth, and/or development policy? What are its key implications and predictions? What are its shortcomings? 

## Question 2

Explain why an autocrat (whether it be a Medieval King/Queen or a modern dictator) may not be as all powerful as they look. What does their rule depend upon, and what tradeoffs must they make? Use at least two different models/theoretical frameworks to support your answer.

## Question 3

Explain two theories or frameworks for understanding how Western Europe emerged out of 1,000 years of feudalism.

## Question 4

Explain why foreign aid (intended specifically for stimulating economic development) has largely failed to accomplish its goal.

## Question 5

Explain the role of creative destruction in both promoting and preventing economic development.

## Question 6

Explain the "violence trap." If rent-seeking, patronage privileges, and restricted access is so harmful to markets and innovation, what is wrong with recommending to developing countries to remove these barriers and privileges, and implement equal rule of law?

# Section II (Opinions) — Choose Two (2)

## Question 7

What, in your opinion, is the role of geography in explaining the differences (both historical and present-day) in economic development around the world? Be precise.

## Question 8

One proposed solution to the problem of transplanting good institutions into developing countries are special economic zones and/or "*charter cities*." This was, at one time, favored by Paul Romer. The idea is to create an autonomous new city (on empty land) in a developing country that is to have *different* institutions (law, governance, etc) from the rest of the developing country. Local citizens of the country will be allowed to immigrate into the city, and it will attract foreign investment. The city's institutions might be modeled on successful developed countries, or even run by them (via governments, nonprofits, entrepreneurs, etc). What do you think of this idea?

## Question 9

Critically appraise mercantilism as a historical economic and political philosophy. Explain the philosophy of mercantilism, the policy prescriptions behind it. Do you think mercantilism, given the economic history of trade and political-economic systems, deserves the sullied reputation it has today among most economists and policymakers? 

## Question 10

What idea, reading, and/or concept(s) this semester was your favorite, or you found most interesting or surprising, and why?